# Generated by Django 5.0.4 on 2024-05-16 20:08

import api.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('committee', models.CharField(blank=True, max_length=20)),
                ('manager', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('serial', models.CharField(blank=True, max_length=40)),
                ('price', models.DecimalField(decimal_places=2,
                 default=0, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2,
                 default=0, max_digits=10, null=True)),
                ('bought_at', models.DateField(null=True)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
