# Generated by Django 5.0.4 on 2024-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_bought_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bought_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='serial',
        ),
        migrations.AddField(
            model_name='item',
            name='bought_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
