# Generated by Django 5.0.4 on 2024-06-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_created_at_remove_item_updated_at_and_more'),
        ('api', '0006_alter_item_bought_at_alter_item_created_at_and_more'),
    ]

    operations = [
    ]
