# Generated by Django 5.0.4 on 2024-06-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_created_at_item_updated_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
